AWSTemplateFormatVersion: '2010-09-09'
Description: "flows util"
Parameters:
  MailgunApiKey:
    Type: String
Resources:
  tempfileFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: tempfile
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
      Environment:
        Variables:
          DataBucket:
            Ref: DataBucket
  TimerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: timer
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs6.10
      Timeout: 300
  dedupFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: dedup
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs6.10
      Timeout: 300
  json2stringFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: json2string
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs6.10
      Timeout: 300
  string2jsonFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: string2json
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs6.10
      Timeout: 300
  sendmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: sendmail
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
      Environment:
        Variables:
          MailgunApiKey:
            Ref: MailgunApiKey
  manualtriggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: manualtrigger
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs6.10
      Timeout: 300
  timestamp2datetimeFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: timestamp2datetime
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs6.10
      Timeout: 300
  todayFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: today
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs8.10
      Timeout: 300
  tempfileLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: tempfileFunction
      RetentionInDays: 7
  TimerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: TimerFunction
      RetentionInDays: 7
  dedupLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: dedupFunction
      RetentionInDays: 7
  json2stringLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: json2stringFunction
      RetentionInDays: 7
  string2jsonLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: string2jsonFunction
      RetentionInDays: 7
  sendmailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: sendmailFunction
      RetentionInDays: 7
  manualtriggerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: manualtriggerFunction
      RetentionInDays: 7
  timestamp2datetimeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: timestamp2datetimeFunction
      RetentionInDays: 7
  todayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: todayFunction
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - s3:*
              Resource: "*"
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 5
            Status: Enabled
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ TimerFunction , Arn ]
              - Fn::GetAtt: [ tempfileFunction , Arn ]
              - Fn::GetAtt: [ dedupFunction , Arn ]
              - Fn::GetAtt: [ json2stringFunction , Arn ]
              - Fn::GetAtt: [ string2jsonFunction , Arn ]
              - Fn::GetAtt: [ sendmailFunction , Arn ]
              - Fn::GetAtt: [ manualtriggerFunction , Arn ]
              - Fn::GetAtt: [ timestamp2datetimeFunction , Arn ]
              - Fn::GetAtt: [ todayFunction , Arn ]
Outputs:
  TimerFunction:
    Description: 'timer'
    Value:
      Fn::GetAtt: [ TimerFunction , Arn ]
  TimerRole:
    Description: 'timer'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  tempfileFunction:
    Description: 'tempfile'
    Value:
      Fn::GetAtt: [ tempfileFunction , Arn ]
  tempfileRole:
    Description: 'tempfile'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  dedupFunction:
    Description: 'dedup'
    Value:
      Fn::GetAtt: [ dedupFunction , Arn ]
  dedupRole:
    Description: 'dedup'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  json2stringFunction:
    Description: 'json2string'
    Value:
      Fn::GetAtt: [ json2stringFunction , Arn ]
  json2stringRole:
    Description: 'json2string'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  string2jsonFunction:
    Description: 'string2json'
    Value:
      Fn::GetAtt: [ string2jsonFunction , Arn ]
  string2jsonRole:
    Description: 'string2json'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  sendmailFunction:
    Description: 'sendmail'
    Value:
      Fn::GetAtt: [ sendmailFunction , Arn ]
  sendmailRole:
    Description: 'sendmail'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  manualtriggerFunction:
    Description: 'manualtrigger'
    Value:
      Fn::GetAtt: [ manualtriggerFunction , Arn ]
  manualtriggerRole:
    Description: 'manualtrigger'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  timestamp2datetimeFunction:
    Description: 'timestamp2datetime'
    Value:
      Fn::GetAtt: [ timestamp2datetimeFunction , Arn ]
  timestamp2datetimeRole:
    Description: 'timestamp2datetime'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  todayodayFunction:
    Description: 'today'
    Value:
      Fn::GetAtt: [ todayFunction , Arn ]
  todayRole:
    Description: 'today'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
